version: '3.8'
networks:
  Prom-net:
    driver: bridge
services:
  csvserver:
    image: infracloudio/csvserver:latest
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - 9090
    ports: 
      - "9090:9090"
    networks:
      - Prom-net